### ISSUE TITLE
styles.css

### ISSUE THREAD

**Issue by danmarsden** [marcusgreen/moodle-qbehaviour_interactiveexplain#3]
shouldn't this:
https://github.com/marcusgreen/moodle-qbehaviour_interactiveexplain/blob/master/styles.css#L1

be:
que.interactiveexplain .explanation_header

**Comment by marcusgreen** [comment]
That would be true if there was a question type called interactiveexplain but typically it will be under something like que.gapfill .explanation_header. Though I only realised I should have the .que in there just before I submitted it.

**Comment by danmarsden** [comment]
cool - feel free to close it then! :-)
