### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [marcusgreen/moodle-qbehaviour_interactiveexplain#4]
Moodle implements a privacy api - it would be nice if you could implement this in your plugin. Sites that use continuous integration processes will not be able to use your plugin as Moodle includes unit tests to check that all installed plugins contain appropriate privacy classes.
more information on the privacy api is here:
https://docs.moodle.org/dev/Privacy_API

please note - this is not a blocker for approval in the plugins db but would be nice to add at some point.

**Comment by marcusgreen** [comment]
Thanks Dan, Have added the null provider privacy API classes, pushed to github and done a release to the plugins database.
